#!/usr/bin/env python

from __future__ import print_function, unicode_literals

import sys
import os.path


def main():
    for arg in sys.argv[1:]:
        _, ext = os.path.splitext(arg)
        print(ext.lstrip('.'))

if __name__ == '__main__':
    main()
