#!/bin/bash

shopt -s extglob


usage()
{
    echo    "Simple, yet useful git command to set current JIRA ticket you are working on."
    echo    "Saves time - set once, and it will auto-append JIRA ticket code to your commit messages."
    echo
    echo    "Usage:"
    echo -e "\tgit jira [-arg1, --arg2...]"
    echo -e "\t\tcommit with current JIRA ticket code. Args are passed to 'git commit'."
    echo -e "\tgit jira set [CODE]"
    echo -e "\t\tset current JIRA ticket to 'CODE', if specified, or clean existing one."
    echo -e "\tgit jira show"
    echo -e "\t\tshow current JIRA ticket code."
    echo -e "\tgit jira file"
    echo -e "\t\tshow the file path where the ticket code is stored."
}


ticket_file()
{
    echo "$(git rev-parse --show-toplevel)/.git/JIRA_TICKET"    
}

ticket_clean()
{
    rm -f $(ticket_file)
    echo "Current JIRA ticket code cleaned."
}

ticket_commit()
{
    if [ -f $(ticket_file) ]; then
        git commit $@ --template $(ticket_file)
    else
        git commit $@
    fi
}


case "$1" in
    set )
        if [ -z "$2" ]; then
            ticket_clean
        else
            echo "$2" > $(ticket_file)
            echo "Set JIRA ticket to '$2'."
        fi
        ;;

    clean )
        ticket_clean
        ;;

    show )
        # supress possible errors
        ticket=`cat $(ticket_file) 2>/dev/null`

        if [ -z $ticket ]; then
            echo "Current JIRA ticket is not set. Use 'git jira set' command to set it."
        else
            echo "Current JIRA ticket: '$ticket'"
        fi
        ;;

    commit | "" )
        shift
        ticket_commit $@
        ;;

    file )
        echo $(ticket_file)

        if [ ! -e $(ticket_file) ]; then
            echo "Note that this file does not exist, as JIRA ticket is not set."
        fi
        ;;

    -* )
        ticket_commit $@
        ;;

    help | -h)
        usage
        ;;

    * )
        echo "Unknown command."
        ;;

esac
