#!/usr/bin/env python
from __future__ import division, print_function
import sys


def main():
    expr = ' '.join(sys.argv[1:])
    try:
        result = eval(expr)
    except Exception as exc:
        print(str(exc), file=sys.stderr)
    else:
        print(result)


if __name__ == '__main__':
    main()
